# https://supabase.com/docs/guides/cli/config
# Link dit project met: supabase link --project-ref <ref>

[functions.sync-server-status]
verify_jwt = false

[functions.sync-kmr-data]
verify_jwt = false

[functions.sync-results]
verify_jwt = false

[functions.sync-ratings-v2]
verify_jwt = false

[functions.manage-blocklist]
verify_jwt = true

[functions.steam-auth]
verify_jwt = false
